# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3898bc150770a1dba66d4134649c1dcc84ee7d48bd01f6bbf477af3e40a2a3bfeb97f9abeab8ce3fc582f45c117f50386956a4cf4923f843e6eac361fd2882d9
  http_basic_auth_user: 'admin'
  http_basic_auth_password: 'baozi'

test:
  secret_key_base: 11272c16cdf2cc9cd1d3a49fa58ae86eb121ea20d5daf05ad405ae03a32580dd8ac2ea6ddae0053b4bc01bf9505373069e47d660b241177912e2219059b9a91d
  http_basic_auth_user: 'admin'
  http_basic_auth_password: 'baozi'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  http_basic_auth_user: <%= ENV["ZHI_USER"] %>
  http_basic_auth_password: <%= ENV["ZHI_PASSWORD"] %>
